INSERT INTO T_CAR_INVENTORY(NAME,CREATED_BY) VALUES ('Toyota Camry', 'robot');
INSERT INTO T_CAR_INVENTORY(NAME,CREATED_BY) VALUES ('Toyota Camry', 'robot');
INSERT INTO T_CAR_INVENTORY(NAME,CREATED_BY) VALUES ('BMW 650', 'robot');
INSERT INTO T_CAR_INVENTORY(NAME,CREATED_BY) VALUES ('BMW 650', 'robot');