DROP TABLE IF EXISTS T_CAR_INVENTORY;
CREATE TABLE T_CAR_INVENTORY(ID BIGINT AUTO_INCREMENT PRIMARY KEY , NAME VARCHAR (50), LOCK_ID VARCHAR (50), CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP , CREATED_BY VARCHAR (50), UPDATE_TIME TIMESTAMP, UPDATED_BY VARCHAR (50));
CREATE INDEX IDX_CAR_INV_LOCK_ID ON T_CAR_INVENTORY(LOCK_ID);

DROP TABLE IF EXISTS T_CAR_RENTAL;
CREATE TABLE T_CAR_RENTAL(ID BIGINT AUTO_INCREMENT PRIMARY KEY, CAR_ID INT, CAR_MODEL VARCHAR (50), CUSTOMER VARCHAR (50), START_DATE TIMESTAMP, DUE_DATE TIMESTAMP);
CREATE INDEX IDX_CAR_RENT_CUSTOMER ON T_CAR_RENTAL(CUSTOMER);
CREATE INDEX IDX_CAR_RENT_CAR_NAME ON T_CAR_RENTAL(CAR_MODEL);

DROP TABLE IF EXISTS T_CAR_RENTAL_HIS;
CREATE TABLE T_CAR_RENTAL_HIS(ID BIGINT PRIMARY KEY, CAR_ID INT, CAR_MODEL VARCHAR (50), CUSTOMER VARCHAR (50), START_DATE TIMESTAMP, DUE_DATE TIMESTAMP);
CREATE INDEX IDX_CAR_RENT_HIS_CUSTOMER ON T_CAR_RENTAL_HIS(CUSTOMER);
CREATE INDEX IDX_CAR_RENT_HIS_CAR_NAME ON T_CAR_RENTAL_HIS(CAR_MODEL);